### ISSUE TITLE
Suggestion: renaming the cookbook so it can be published to Chef supermarket

### ISSUE THREAD

**Issue by vitalis** [priestjim/chef-rundeck#24]
It will be great if this cookbook will be published to Chef supermarket.
There is another cookbook with same name already published there(one I really don't like).
A new name can be something like: `rundeck-by-priestjim` or `priestjim-rundeck`

**Comment by priestjim** [comment]
I agree with you but I have yet to figure out a way to upload new cookbooks to Supermarket. The documentation is horrible!

**Comment by spuder** [comment]
To share on the supermarket (Change "Operating System & Virtualization" to the appropriate category listed here: 

https://docs.chef.io/knife_cookbook_site.html


    knife cookbook site share "foobar" "Operating Systems & Virtualization" -z --dry-run


Or use stove

https://github.com/sethvargo/stove

**Comment by priestjim** [comment]
Published it at https://supermarket.chef.io/cookbooks/rundeck-alt

**Comment by akshah123** [comment]
unfortunately, the publish version doesn't work as the resources are still required to use rundeck as the cookbook name.
