### ISSUE TITLE
Possibility of merging our fork

### ISSUE THREAD

**Issue by coderanger** [priestjim/chef-rundeck#9]
Over at https://github.com/balanced-cookbooks/rundeck I've rebuilt this cookbook on top of the Poise structure (resource based, etc). This allows things like creating jobs via a resource:

```ruby
rundeck_job 'example' do
  source 'example.yml.erb'
  options do
    project node['myapp']['project']
    env node.chef_environment
  end
end
```

Would you be interested in merging this with your repo?
end

**Comment by spuder** [comment]
+1 Is this still planned?

**Comment by priestjim** [comment]
I'm waiting for feedback from @coderanger

**Comment by coderanger** [comment]
No, this is no longer an option.
